###회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "nickname": "sj1234",
  "password": "1234asdfg1@"
}

###로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "nickname": "sj1234",
  "password": "1234asdfg1@"
}

###글 쓰기
POST http://localhost:8080/dev/post
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NjAxMTc3OX0._49cAvgRPT11EvYka7Ivi-27Lsab0E_f6wasmif1TbJIgCeK6A5oPjFih98NOf_bbpvTXO9CS7tFlHyChgXRnw
Content-Type: application/json

{
  "title": "제목",
  "contents": "컨텐츠"
}
###전체 글 불러오기
###글 쓰기
GET http://localhost:8080/dev/auth/post
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NjAxMTc3OX0._49cAvgRPT11EvYka7Ivi-27Lsab0E_f6wasmif1TbJIgCeK6A5oPjFih98NOf_bbpvTXO9CS7tFlHyChgXRnw

###글 수정
PUT http://localhost:8080/dev/post/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NjAxMTc3OX0._49cAvgRPT11EvYka7Ivi-27Lsab0E_f6wasmif1TbJIgCeK6A5oPjFih98NOf_bbpvTXO9CS7tFlHyChgXRnw
Content-Type: application/json

{
  "title": "제목22",
  "contents": "컨텐츠22"
}

###댓글쓰기
POST http://localhost:8080/dev/comment
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NjAwODM1Nn0.DqYK_HsVX8i88pSA-SWS4V61DBS6smCOS2euuu7xevNQ7tyt3Dr4Nw41oJ4kQoBpqGWPwhPO54xf3LPlC-LQRQ
Content-Type: application/json

{
  "postId": 1,
  "comments": "댓글댓글입니다"
}

###일반API요청
GET http://localhost:8080/member/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NTY2NjkyMn0.ldhqr7AAedIvhqFpNsJlr0lgCV48npbPC0FMTpjyTQO5ikKg98Ww5H47e85U_EWdpQc0G3cKVWp435ngjcPZQg

###토큰 재발급
POST http://localhost:8080/auth/reissue
Content-Type: application/json

{
  "accessToken": " eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NTYxNDEyNn0.AbiE7eFd5l7pPvZycIdqPUBnsimMkGlsXlLoMWIq3DwxVfdGxb8bOKIDy0j-2DbUC1lLAFBJF_nsihxJXD7-Uw",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NjYyMTcxMjZ9.5RyEhptEeD-0kJQ7SEDISCgnEPZVJlivVouqM4DQ5YiUXFzDvHu4L8dYSX7UU5C5igwhRasa27ExyoeO-W_pDQ"
}

###멤버 미
GET http://localhost:8080/
